name: Add 'All' Team to New Repositories

on:
  schedule:
    - cron: "* * * * *"

jobs:
  add_all_team:
    runs-on: ubuntu-latest
    steps:
      - name: Add 'All' Team to New Repos
        uses: actions/github-script@v5
        with:
          script: |
            const { Octokit } = require('@octokit/core');
            const octokit = new Octokit({ auth: "${{ secrets.PAT }}" });

            const orgName = 'ecohealthalliance';
            const teamName = 'All';

            const { data: teams } = await octokit.request('GET /orgs/{org}/teams', { org: orgName });
            const targetTeam = teams.find(team => team.name === teamName);
            if (!targetTeam) {
              console.log(`Team "${teamName}" not found.`);
              return;
            }

            const { data: orgRepos } = await octokit.request('GET /orgs/{org}/repos', { org: orgName });

            for (const repo of orgRepos) {
              try {
                await octokit.request('PUT /teams/{team_id}/repos/{owner}/{repo}', {
                  team_id: targetTeam.id,
                  owner: repo.owner.login,
                  repo: repo.name,
                  permission: 'pull'
                });
                console.log(`Added 'All' team to ${repo.full_name}`);
              } catch (error) {
                console.error(`Failed to add 'All' team to ${repo.full_name}: ${error.message}`);
              }
            }
