name: Add All Team to New Repository

on:
  repository_dispatch:
    types: [repository_created]

jobs:
  add_all_team:
    runs-on: ubuntu-latest
    steps:
    - name: Add All team to the new repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TEAM_ID: 2981406
      run: |
        curl -X PUT \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: token $GITHUB_TOKEN" \
        https://api.github.com/organizations/${{ github.event.client_payload.organization_id }}/team/$TEAM_ID/repos/${{ github.event.client_payload.repository_full_name }}
